stages:
  preprocess:
    cmd: python ./src/dvc_pipeline/0_preprocess.py
    deps:
    - ./src/dvc_pipeline/0_preprocess.py
    params:
    - preprocess.char_per_words
    - preprocess.word_count
    - preprocess.comment_len
    outs:
    - ./data/processed/

  transform:
    cmd: python ./src/dvc_pipeline/1_vetorisation.py
    deps:
    - ./src/dvc_pipeline/1_vetorisation.py
    params:
    - transform.ngram_range
    - transform.no_of_features
    - transform.standardise
    outs:
    - ./data/transformed/

  imb:
    cmd: python ./src/dvc_pipeline/2_imb_handling.py
    deps:
    - ./src/dvc_pipeline/2_imb_handling.py
    params:
    - imb.test_size
    outs:
    - ./data/train_test_split/

  model:
    cmd: python ./src/dvc_pipeline/3_model.py
    deps:
    - ./src/dvc_pipeline/3_model.py
    outs:
    - ./models/
    # params:
    # - model.try_model
    # - model.tune_gradient_boosting
    # - model.tune_random_forest
    # - model.tune_XGBoost
    # - model.tune_light_boost
  # best_model:
  #   cmd: python ./src/dvc_pipeline/4_save_best_model.py
  #   deps:
  #   - ./src/dvc_pipeline/4_save_best_model.py
  #   outs:
  #   - ./model/