stages:
  preprocess:
    cmd: python ./src/dvc_pipeline/0_preprocess.py
    deps:
    - ./src/dvc_pipeline/0_preprocess.py
    params:
    - preprocess.char_per_words
    - preprocess.word_count
    - preprocess.comment_len
    outs:
    - ./data/processed/

  transform:
    cmd: python ./src/dvc_pipeline/1_vetorisation.py
    deps:
    - ./src/dvc_pipeline/1_vetorisation.py
    params:
    - transform.ngram_range
    - transform.no_of_features
    - transform.standardise
    - transform.test_size
    outs:
    - ./data/train_test_split/

  imb:
    cmd: python ./src/dvc_pipeline/2_imb_handling.py
    deps:
    - ./src/dvc_pipeline/2_imb_handling.py
    params:
    - imb.over_sampling_tech
    outs:
    - ./data/oversampled/

  model:
    cmd: python ./src/dvc_pipeline/3_model.py
    deps:
    - ./src/dvc_pipeline/3_model.py
    params:
    - model.tune_xgb
    - model.tune_rf
    - model.try_models
  dl:
    cmd: python ./src/dvc_pipeline/4_dl.py
    deps:
    - ./src/dvc_pipeline/4_dl.py
    params:
    - dl.model
    
  register_model:
    cmd: python ./src/dvc_pipeline/5_register_model.py
    deps:
    - ./src/dvc_pipeline/5_register_model.py
    params:
    - register_model.register

  model_report:
    cmd: python ./src/dvc_pipeline/6_model_report.py
    params:
    - model_report.best_model_version
    - model_report.best_model_name
    - model_report.generate_report
    outs:
    - ./reports