preprocess:
  comment_len: True
  word_count: True
  char_per_words: True

imb:
  over_sampling_tech: none
  
transform:
  test_size: 0.2
  standardise: False
  no_of_features: 2000
  ngram_range: 1,2
  count_vec: False

model:
  tune_xgb: False
  tune_rf: False
  try_models: True

dl:
  model: False

register_model:
  register: False

model_report:
  best_model_name: best_model_ann
  best_model_version: 2
  generate_report: False