preprocess:
  comment_len: True
  word_count: True
  char_per_words: True

imb:
  test_size: 0.2
  over_sampling_tech: SMOTE
transform:
  standardise: False
  no_of_features: 2000
  ngram_range: 1,2
  count_vec: True